using System.Reflection;
using Dreamine.Database.Abstractions.Mapping;

namespace Dreamine.Database.Core.Mapping;

/// <summary>
/// Describes database mapping metadata for an entity property.
/// </summary>
public sealed class DatabasePropertyMap
{
    private DatabasePropertyMap(PropertyInfo property, string columnName, bool isKey, bool isGenerated)
    {
        Property = property;
        ColumnName = columnName;
        IsKey = isKey;
        IsGenerated = isGenerated;
    }

    /// <summary>
    /// Gets the mapped CLR property.
    /// </summary>
    public PropertyInfo Property { get; }

    /// <summary>
    /// Gets the mapped database column name.
    /// </summary>
    public string ColumnName { get; }

    /// <summary>
    /// Gets the non-nullable CLR property type used for database type mapping.
    /// </summary>
    public Type PropertyType => Nullable.GetUnderlyingType(Property.PropertyType) ?? Property.PropertyType;

    /// <summary>
    /// Gets whether the property is the entity key.
    /// </summary>
    public bool IsKey { get; }

    /// <summary>
    /// Gets whether the property value is generated by the database.
    /// </summary>
    public bool IsGenerated { get; }

    /// <summary>
    /// Creates mapping metadata for a CLR property.
    /// </summary>
    /// <param name="property">The CLR property.</param>
    /// <returns>The property map.</returns>
    public static DatabasePropertyMap Create(PropertyInfo property)
    {
        ArgumentNullException.ThrowIfNull(property);

        var columnName = property.GetCustomAttribute<DatabaseColumnAttribute>()?.Name ?? property.Name;
        var isKey = property.GetCustomAttribute<DatabaseKeyAttribute>() is not null ||
                    string.Equals(property.Name, "Id", StringComparison.OrdinalIgnoreCase);
        var isGenerated = property.GetCustomAttribute<DatabaseGeneratedAttribute>() is not null;

        return new DatabasePropertyMap(property, columnName, isKey, isGenerated);
    }
}
