using System.Reflection;
using Dreamine.Database.Abstractions.Mapping;

namespace Dreamine.Database.Core.Mapping;

/// <summary>
/// \if KO
/// <para>엔터티 속성의 데이터베이스 매핑 메타데이터를 설명합니다.</para>
/// \endif
/// \if EN
/// <para>Describes database-mapping metadata for an entity property.</para>
/// \endif
/// </summary>
public sealed class DatabasePropertyMap
{
    /// <summary>
    /// \if KO
    /// <para>분석된 CLR 속성과 열 매핑 정보로 인스턴스를 초기화합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Initializes an instance with the analyzed CLR property and column-mapping information.</para>
    /// \endif
    /// </summary>
    /// <param name="property">
    /// \if KO
    /// <para>매핑된 CLR 속성입니다.</para>
    /// \endif
    /// \if EN
    /// <para>The mapped CLR property.</para>
    /// \endif
    /// </param>
    /// <param name="columnName">
    /// \if KO
    /// <para>매핑된 데이터베이스 열 이름입니다.</para>
    /// \endif
    /// \if EN
    /// <para>The mapped database column name.</para>
    /// \endif
    /// </param>
    /// <param name="isKey">
    /// \if KO
    /// <para>속성이 엔터티 키인지 여부입니다.</para>
    /// \endif
    /// \if EN
    /// <para>Whether the property is the entity key.</para>
    /// \endif
    /// </param>
    /// <param name="isGenerated">
    /// \if KO
    /// <para>값이 데이터베이스에서 생성되는지 여부입니다.</para>
    /// \endif
    /// \if EN
    /// <para>Whether the value is generated by the database.</para>
    /// \endif
    /// </param>
    private DatabasePropertyMap(PropertyInfo property, string columnName, bool isKey, bool isGenerated)
    {
        Property = property;
        ColumnName = columnName;
        IsKey = isKey;
        IsGenerated = isGenerated;
    }

    /// <summary>
    /// \if KO
    /// <para>매핑된 CLR 속성을 가져옵니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets the mapped CLR property.</para>
    /// \endif
    /// </summary>
    public PropertyInfo Property { get; }

    /// <summary>
    /// \if KO
    /// <para>매핑된 데이터베이스 열 이름을 가져옵니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets the mapped database column name.</para>
    /// \endif
    /// </summary>
    public string ColumnName { get; }

    /// <summary>
    /// \if KO
    /// <para>데이터베이스 형식 매핑에 사용할 null 비허용 CLR 속성 형식을 가져옵니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets the non-nullable CLR property type used for database type mapping.</para>
    /// \endif
    /// </summary>
    public Type PropertyType => Nullable.GetUnderlyingType(Property.PropertyType) ?? Property.PropertyType;

    /// <summary>
    /// \if KO
    /// <para>속성이 엔터티 키인지 여부를 가져옵니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets whether the property is the entity key.</para>
    /// \endif
    /// </summary>
    public bool IsKey { get; }

    /// <summary>
    /// \if KO
    /// <para>속성 값이 데이터베이스에서 생성되는지 여부를 가져옵니다.</para>
    /// \endif
    /// \if EN
    /// <para>Gets whether the property value is generated by the database.</para>
    /// \endif
    /// </summary>
    public bool IsGenerated { get; }

    /// <summary>
    /// \if KO
    /// <para>CLR 속성의 데이터베이스 매핑 메타데이터를 만듭니다.</para>
    /// \endif
    /// \if EN
    /// <para>Creates database-mapping metadata for a CLR property.</para>
    /// \endif
    /// </summary>
    /// <param name="property">
    /// \if KO
    /// <para>분석할 CLR 속성입니다.</para>
    /// \endif
    /// \if EN
    /// <para>The CLR property to analyze.</para>
    /// \endif
    /// </param>
    /// <returns>
    /// \if KO
    /// <para>분석된 속성 매핑입니다.</para>
    /// \endif
    /// \if EN
    /// <para>The analyzed property map.</para>
    /// \endif
    /// </returns>
    /// <exception cref="ArgumentNullException">
    /// \if KO
    /// <para><paramref name="property"/>가 <see langword="null"/>인 경우 발생합니다.</para>
    /// \endif
    /// \if EN
    /// <para>Thrown when <paramref name="property"/> is <see langword="null"/>.</para>
    /// \endif
    /// </exception>
    public static DatabasePropertyMap Create(PropertyInfo property)
    {
        ArgumentNullException.ThrowIfNull(property);

        var columnName = property.GetCustomAttribute<DatabaseColumnAttribute>()?.Name ?? property.Name;
        var isKey = property.GetCustomAttribute<DatabaseKeyAttribute>() is not null ||
                    string.Equals(property.Name, "Id", StringComparison.OrdinalIgnoreCase);
        var isGenerated = property.GetCustomAttribute<DatabaseGeneratedAttribute>() is not null;

        return new DatabasePropertyMap(property, columnName, isKey, isGenerated);
    }
}
